### ISSUE TITLE
nvdashboard stopped working with nvcr.io/nvidia/pytorch:22.08-py3

### ISSUE THREAD

**Issue by AHarouni** [rapidsai/jupyterlab-nvdashboard#139]
I have a docker file based on 
```
FROM nvcr.io/nvidia/pytorch:22.08-py3
RUN pip3 install jupyterlab-nvdashboard jupyterlab-tensorboard-pro
```
Which used to work fine for a couple of month.
I started rebuilding it in October and I am getting the pannels to show up but no gpus metric appear. also and 500 internal error as show below.

I also tested the latest 
- `pip install --upgrade --pre jupyterlab-nvdashboard` but no luck
- using different base as `FROM nvcr.io/nvidia/pytorch:22.09-py3` but still same error 

![image](https://user-images.githubusercontent.com/61221417/201756661-451d576b-95f1-4baf-87ec-11e642f58f7e.png)

**Comment by saumikn** [comment]
I can confirm that I'm getting the same issue using `FROM nvidia/cuda:11.6.0-base-ubuntu20.04` as my base container. 

![image](https://user-images.githubusercontent.com/5565119/201770922-1da71882-5ae7-46ad-be6f-e8d662529ae8.png)

However, when I use the older container `FROM rapidsai/rapidsai:22.10-cuda11.5-runtime-ubuntu20.04-py3.9` (on the same machine), the dashboard works as normal. Did something change so that the dashboard doesn't work anymore? I would prefer to use a later base ubuntu container, instead of an older container.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. Bokeh v3 was released recently, so perhaps this has broken things. 

Could you try:

```
RUN pip3 install jupyterlab-nvdashboard jupyterlab-tensorboard-pro bokeh==2
```

cc @bryevdv

**Comment by saumikn** [comment]
I added jupyterlab-tensorboard-pro and bokeh==2 to my pip install, which did not solve the issue, the errors still come up.


When I try to open Machine Resources, GPU Utilization, etc, here are the error logs:
```
Uncaught exception GET /Machine-Resources (127.0.0.1)
HTTPServerRequest(protocol='http', host='compute1-exec-196.ris.wustl.edu:8228', method='GET', uri='/Machine-Resources', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    session = await self.get_session()
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/contexts.py", line 242, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/application.py", line 192, in initialize_document
    h.modify_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/cpu.py", line 87, in resource_timeline
    disk_fig.line(source=source, x="time", y="disk-read", color="blue", legend="Read")
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/plotting/_decorators.py", line 87, in wrapped
    return create_renderer(glyphclass, self.plot, **kwargs)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/plotting/_renderer.py", line 133, in create_renderer
    update_legend(plot, legend_kwarg, glyph_renderer)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/plotting/_legends.py", line 57, in update_legend
    _LEGEND_KWARG_HANDLERS[kwarg](value, legend, glyph_renderer)
KeyError: 'legend'
500 GET /Machine-Resources (127.0.0.1) 92.60ms
[E 2022-11-17 16:07:15.935 ServerApp] {
      "Host": "compute1-exec-196.ris.wustl.edu:8228",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
    }
[E 2022-11-17 16:07:15.935 ServerApp] 500 GET /nvdashboard/Machine-Resources (10.225.22.152) 99.18ms referer=None
[I 2022-11-17 16:07:18.857 ServerApp] Trying to establish websocket connection to ws://localhost:45847/GPU-Utilization/ws
[I 2022-11-17 16:07:18.859 ServerApp] Websocket connection established to ws://localhost:45847/GPU-Utilization/ws
[I 2022-11-17 16:07:19.986 ServerApp] Trying to establish websocket connection to ws://localhost:45847/GPU-Memory/ws
[I 2022-11-17 16:07:19.988 ServerApp] Websocket connection established to ws://localhost:45847/GPU-Memory/ws
Uncaught exception GET /GPU-Resources (127.0.0.1)
HTTPServerRequest(protocol='http', host='compute1-exec-196.ris.wustl.edu:8228', method='GET', uri='/GPU-Resources', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    session = await self.get_session()
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/contexts.py", line 242, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/application.py", line 192, in initialize_document
    h.modify_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 547, in gpu_resource_timeline
    tot_fig.line(
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/plotting/_decorators.py", line 87, in wrapped
    return create_renderer(glyphclass, self.plot, **kwargs)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/plotting/_renderer.py", line 133, in create_renderer
    update_legend(plot, legend_kwarg, glyph_renderer)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/plotting/_legends.py", line 57, in update_legend
    _LEGEND_KWARG_HANDLERS[kwarg](value, legend, glyph_renderer)
KeyError: 'legend'
500 GET /GPU-Resources (127.0.0.1) 82.71ms
[E 2022-11-17 16:07:20.815 ServerApp] {
      "Host": "compute1-exec-196.ris.wustl.edu:8228",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
    }
[E 2022-11-17 16:07:20.815 ServerApp] 500 GET /nvdashboard/GPU-Resources (10.225.22.152) 85.00ms referer=None
[I 2022-11-17 16:07:22.357 ServerApp] Trying to establish websocket connection to ws://localhost:45847/PCIe-Throughput/ws
[I 2022-11-17 16:07:22.508 ServerApp] Websocket connection established to ws://localhost:45847/PCIe-Throughput/ws
GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-8f12d526-b5db-6c33-60c9-a338be600e8f)
Warning: Setting counter control is deprecated!

Uncaught exception GET /NVLink-Throughput (127.0.0.1)
HTTPServerRequest(protocol='http', host='compute1-exec-196.ris.wustl.edu:8228', method='GET', uri='/NVLink-Throughput', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    session = await self.get_session()
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/contexts.py", line 242, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/application.py", line 192, in initialize_document
    h.modify_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 235, in nvlink
    nvlink_state["tx"] = [
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 237, in <listcomp>
    [
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 238, in <listcomp>
    pynvml.nvmlDeviceGetNvLinkUtilizationCounter(
  File "/home/n.saumik/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 2723, in nvmlDeviceGetNvLinkUtilizationCounter
    _nvmlCheckReturn(ret)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
500 GET /NVLink-Throughput (127.0.0.1) 53.21ms
[E 2022-11-17 16:07:22.890 ServerApp] {
      "Host": "compute1-exec-196.ris.wustl.edu:8228",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
    }
[E 2022-11-17 16:07:22.890 ServerApp] 500 GET /nvdashboard/NVLink-Throughput (10.225.22.152) 109.84ms referer=None
Uncaught exception GET /NVLink-Timeline (127.0.0.1)
HTTPServerRequest(protocol='http', host='compute1-exec-196.ris.wustl.edu:8228', method='GET', uri='/NVLink-Timeline', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    session = await self.get_session()
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/server/contexts.py", line 242, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/application.py", line 192, in initialize_document
    h.modify_document(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 397, in nvlink_timeline
    nvlink_state["tx"] = [
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 399, in <listcomp>
    [
  File "/home/n.saumik/.local/lib/python3.10/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 400, in <listcomp>
    pynvml.nvmlDeviceGetNvLinkUtilizationCounter(
  File "/home/n.saumik/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 2723, in nvmlDeviceGetNvLinkUtilizationCounter
    _nvmlCheckReturn(ret)
  File "/home/n.saumik/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
500 GET /NVLink-Timeline (127.0.0.1) 75.96ms
[E 2022-11-17 16:07:24.046 ServerApp] {
      "Host": "compute1-exec-196.ris.wustl.edu:8228",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
    }
[E 2022-11-17 16:07:24.047 ServerApp] 500 GET /nvdashboard/NVLink-Timeline (10.225.22.152) 266.81ms referer=None
```

**Comment by bryevdv** [comment]
cc @mattpap for layout-related issues. @mattpap this seems similar to the issue reported on Dask that you are looking at?

**Comment by bryevdv** [comment]
> KeyError: 'legend'

@saumikn you must have some environment or install mixup? The `legend` keyword arg was deprecated before 3.0, but it was only actually removed in the 3.0 release.

**Comment by saumikn** [comment]
@bryevdv Here is my [Dockerfile](https://gist.github.com/saumikn/6b53cf100ef7dbea995d959e645b69b1) and [environment.yml](https://gist.github.com/saumikn/7da336d74ebeaf0c8992b34c70255da6) for reference, if there is a different set of packages I need to install to get this to work.

**Comment by bryevdv** [comment]
@saumikn I'm not sure what to tell you. The `legend` keyword was definitely handled Bokeh 2.4:

https://github.com/bokeh/bokeh/blob/branch-2.4/bokeh/plotting/_legends.py#L143

If you are getting `KeyError: 'legend'` then you don't actually have Bokeh 2.4 installed, despite what your `environment.yml` states. I'm not sure why, though.

**Comment by mattpap** [comment]
> (...) this seems similar to the issue reported on Dask that you are looking at?

Almost certainly the same issue.

**Comment by AHarouni** [comment]
Thanks for your response.
using `bokeh==2` broke jupyter lab completly for me. it din't even want to start 
However, I managed to get it to work using `bokeh==2.4`
so this worked for me as 
```
FROM nvcr.io/nvidia/pytorch:22.08-py3
RUN pip install jupyterlab-nvdashboard bokeh==2.4
```

**Comment by saumikn** [comment]
@bryevdv There was a different issue with my environment, but after resolving it, setting `bokeh=2.4.1` worked for the graphs. Thanks for the help!

I'm still getting the 500 service errors for some of them though, but I don't use those panes in the dashboard anyways. Maybe should be fixed for others though?

**Comment by jacobtomlinson** [comment]
Ah sorry I should've been more specific with my bokeh pin suggestion. Glad things are working now with `2.4.1`.

I think the 500 errors you are seeing are related to #114 so I'm going to close out this issue now as resolved and open a new one to track bokeh 3 support specifically.
