### ISSUE TITLE
extension failed loading with message: ExtensionLoadingError('_load_jupyter_server_extension function was not found.')

### ISSUE THREAD

**Issue by rupeshknn** [rapidsai/jupyterlab-nvdashboard#158]
I see this error when running `jupyterlab`. CUDA 12. Any suggestions?

```
jupyterlab_nvdashboard | extension failed loading with message: ExtensionLoadingError('_load_jupyter_server_extension function was not found.')
    Traceback (most recent call last):
      File "/u/rupeshrk/mambaforge/envs/qddev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 356, in load_extension
        extension.load_all_points(self.serverapp)
      File "/u/rupeshrk/mambaforge/envs/qddev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 228, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/u/rupeshrk/mambaforge/envs/qddev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 228, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/u/rupeshrk/mambaforge/envs/qddev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 219, in load_point
        return point.load(serverapp)
      File "/u/rupeshrk/mambaforge/envs/qddev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 146, in load
        loader = self._get_loader()
      File "/u/rupeshrk/mambaforge/envs/qddev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 115, in _get_loader
        loader = get_loader(loc)
      File "/u/rupeshrk/mambaforge/envs/qddev/lib/python3.10/site-packages/jupyter_server/extension/utils.py", line 47, in get_loader
        raise ExtensionLoadingError(msg) from None
    jupyter_server.extension.utils.ExtensionLoadingError: _load_jupyter_server_extension function was not found.
```

**Comment by jakirkham** [comment]
Could you please include `pip list`?

**Comment by jakirkham** [comment]
Glad it is working

If you run into it again, please include the install environment used and commands run

This helps us a lot when it comes to reproducing and debugging issues
