### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by quasiben** [rapidsai/jupyterlab-nvdashboard#19]
When trying to install the jlab components I get an error:

```
> /home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/bin/npm pack jupyterlab-nvdashboard
npm notice
npm notice 📦  jupyterlab-nvdashboard@0.1.9
npm notice === Tarball Contents ===
npm notice 1.3kB package.json
npm notice 2.7kB README.md
npm notice 2.5kB lib/dashboard.d.ts
npm notice 4.5kB lib/dashboard.js
npm notice 247B  lib/index.d.ts
npm notice 2.6kB lib/index.js
npm notice 398B  style/expansion-card-variant-dark.svg
npm notice 398B  style/expansion-card-variant-light.svg
npm notice 1.9kB style/index.css
npm notice === Tarball Details ===
npm notice name:          jupyterlab-nvdashboard
npm notice version:       0.1.9
npm notice filename:      jupyterlab-nvdashboard-0.1.9.tgz
npm notice package size:  5.3 kB
npm notice unpacked size: 16.5 kB
npm notice shasum:        53c2f139d47fe8b18e033f9d8f46d53f871356af
npm notice integrity:     sha512-SqR4wA7zxi1HD[...]jdJCCYG6tw4OQ==
npm notice total files:   9
npm notice
jupyterlab-nvdashboard-0.1.9.tgz

Traceback (most recent call last):

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 82, in start
    ans = self.run_task()

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/commands.py", line 1385, in _install_extension
    errors = _validate_compatibility(extension, deps, core_data)

  File "/home/nfs/bzaitlen/miniconda3/envs/jlab-1.0/lib/python3.7/site-packages/jupyterlab/commands.py", line 1749, in _validate_compatibility
    overlap = _test_overlap(core_deps[key], value)

KeyError: '@jupyterlab/apputils'
```

**Comment by jacobtomlinson** [comment]
Are you running `jlpm install jupyterlab-nvdashboard`?

**Comment by jacobtomlinson** [comment]
This is likely related to the version on Jupyter Lab being too old. I'm going to close this out as there hasn't been a response for a while.

If you're still having trouble feel free to ping me though.
