### ISSUE TITLE
Unable to start nvdashboard

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/jupyterlab-nvdashboard#31]
I received the following error: 
`500 GET /nvdashboard/index.json?1576415340199 (127.0.0.1): could not start nvdashboard in time
`

_Originally posted by @aradhyamathur in https://github.com/rapidsai/jupyterlab-nvdashboard/issues/24#issuecomment-565813462_

**Comment by jacobtomlinson** [comment]
I have been able to reproduce this on a machine without a GPU. Above this error there is also a longer nvml error.

```
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

<details>
<summary>Full traceback</summary>

```
Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 734, in _load_nvml_library
    nvml_lib = CDLL("libnvidia-ml.so.1")
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libnvidia-ml.so.1, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 2, in <module>
    from . import gpu
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 17, in <module>
    pynvml.nvmlInit()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 734, in _load_nvml_library
    nvml_lib = CDLL("libnvidia-ml.so.1")
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libnvidia-ml.so.1, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 2, in <module>
    from . import gpu
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 17, in <module>
    pynvml.nvmlInit()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 734, in _load_nvml_library
    nvml_lib = CDLL("libnvidia-ml.so.1")
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libnvidia-ml.so.1, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 2, in <module>
    from . import gpu
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 17, in <module>
    pynvml.nvmlInit()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 734, in _load_nvml_library
    nvml_lib = CDLL("libnvidia-ml.so.1")
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libnvidia-ml.so.1, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 2, in <module>
    from . import gpu
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 17, in <module>
    pynvml.nvmlInit()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 734, in _load_nvml_library
    nvml_lib = CDLL("libnvidia-ml.so.1")
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libnvidia-ml.so.1, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 2, in <module>
    from . import gpu
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 17, in <module>
    pynvml.nvmlInit()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/Users/jtomlinson/miniconda3/envs/nvdashtest/lib/python3.7/site-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
[W 09:43:18.212 LabApp] 500 GET /nvdashboard/index.json?1576662193193 (::1): could not start nvdashboard in time
```

</details>

@aradhyamathur are you also seeing this same error?

**Comment by david-macleod** [comment]
I'm also seeing this issue, but without the nvml error. I do have GPUs have installed on this server and can call nvidia-smi successfully.

```
[I 13:00:40.731 LabApp] Kernel started: 69c7347e-86ef-4435-9dd1-99c13c6ddba0
[I 13:00:48.322 LabApp] Build is up to date
[W 13:00:48.695 LabApp] zmq message arrived on closed channel
[W 13:00:48.698 LabApp] zmq message arrived on closed channel
[I 13:00:49.525 LabApp] Starting buffering for 69c7347e-86ef-4435-9dd1-99c13c6ddba0:514e1517-dbfa-46e8-8043-6eb332c138af
[W 13:00:49.887 LabApp] 500 GET /nvdashboard/index.json?1594731859780 (192.168.130.203): could not start nvdashboard in time
[E 13:00:49.911 LabApp] {
      "Host": "server1:8890",
      "Connection": "keep-alive",
      "Dnt": "1",
      "X-Xsrftoken": "2|e7e481fe|d4a4d5545dc025208888a3b32d328393|1591180566",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://server1:8890/lab?",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|e7e481fe|d4a4d5545dc025208888a3b32d328393|1591180566; username-server1-8890=\"2|1:0|10:1594731335|43:username-cam2aml01-aml-speechmatics-io-8890|44:ZGQ3OTZiOWM0MTk4NDYyYWExYmM0ZGVlYmJlNmFjODY=|1b86773ac2c38bbc7fcfabc54056651643163ba5b6668f041396fe7193e8b822\""
    }
```
Any ideas?

**Comment by david-macleod** [comment]
Can also confirm I get the `pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found` on a server _without_ GPUs so there seems to be something else going on here.

**Comment by jacobtomlinson** [comment]
The NVML error is expected on a machine without GPUs. We need to handle this cleanly at some stage. But as this is a GPU specific tool I imagine the impact of it not working on non-GPU machines is low.

@david-macleod could you share the traceback that happens to result in the 500?

**Comment by david-macleod** [comment]
Thanks for the quick reply! The traceback is in my original posts, it doesn't give any more info that the 500 error really. I have found that sometimes reloading the jupyter lab web app will allow the GPU dashboard options to appear, but most of the time I just get the 500. Do you have any thoughts why I might see it only sporadically? The error seems to suggests maybe a timeout is at play?

**Comment by jakirkham** [comment]
Maybe some consequence of browser caching?

**Comment by jacobtomlinson** [comment]
Without more logs I'm afraid I can't comment.

**Comment by jacobtomlinson** [comment]
Closing due to inactivity

**Comment by marius311** [comment]
Any chance this could get opened again? I'm seeing this and have a reproducible case / can look up whatever logs you'd like. 

The impact for me is the error:
```
[W 00:31:30.114 LabApp] 500 GET /nvdashboard/index.json?1608107484589 (::1): could not start nvdashboard in time
```
and then a blank System Dashboards tab. 

For me the error is not sporadic but always. However, I will note this cluster has a creaky slow filesystem, lots of things often take really long, so under the theory there's a timeout being hit, would not surprise me if this system hits it every time. 


Other info:
```
$ jupyter serverextension list
config dir: /global/home/users/mariusmillea/.jupyter
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
config dir: /global/software/sl-7.x86_64/modules/langs/python/3.7/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.9 OK

$ jupyter labextension list
JupyterLab v2.2.9
Known labextensions:
   app dir: /global/home/users/mariusmillea/.local/share/jupyter/lab
        @jupyterlab/server-proxy v2.1.1  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        jupyterlab-favorites v2.0.0  enabled  OK
        jupyterlab-nvdashboard v0.4.0  enabled  OK

$ nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 41%   61C    P2    60W / 250W |   9882MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
| 38%   55C    P2    61W / 250W |  11175MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:82:00.0 Off |                  N/A |
| 38%   56C    P2    61W / 250W |   9571MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:83:00.0 Off |                  N/A |
| 23%   34C    P2    56W / 250W |    337MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by jacobtomlinson** [comment]
Sure! Thanks @marius311 I am really keen to get this resolved, I just cannot reproduce it myself.

**Comment by marius311** [comment]
Yea, the command works fine and after forwarding port 8000 to my laptop from this cluster I can see the webpage and its correctly showing the different resource monitors.

**Comment by marius311** [comment]
Fwiw, its about 10 seconds on this system between launching `nvdashboard` and having the webpage accessible.

**Comment by jacobtomlinson** [comment]
> Fwiw, its about 10 seconds on this system between launching nvdashboard and having the webpage accessible.

That's really useful to know. I'm guessing this is the problem here, on my test systems it starts instantly.

I think a solution here would be to extend the timeout that Jupyter server waits for processes to start. I think the default is 10 seconds, I know you can change this via the settings but not sure about entrypoints.

**Comment by jacobtomlinson** [comment]
Ah looks like the [default is 5 seconds](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#server-process-options).

**Comment by jacobtomlinson** [comment]
@marius311 I've raised a PR which will hopefully fix this by extending the timeout. Would you be interested in testing the fix? You should be able to install the PR with 

```
pip install git+https://github.com/jacobtomlinson/jupyterlab-nvdashboard.git@timeout
```

**Comment by marius311** [comment]
Yep, that did it, thank you!
