### ISSUE TITLE
UnicodeDecodeError when install jupyterlab-nvdashboard

### ISSUE THREAD

**Issue by ticlazau** [rapidsai/jupyterlab-nvdashboard#37]
I have the following error when trying to install:

```console
$ jupyter labextension install jupyterlab-nvdashboard
An error occured.
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 23: ordinal not in range(128)
See the log file for details:  /tmp/jupyterlab-debug-_0gasofa.log
```

Log output:

```
/tmp/jupyterlab-debug-m9zg6w9x.log
Yarn configuration loaded.
Node v10.13.0

> /nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/bin/npm pack jupyterlab_tensorboard
Traceback (most recent call last):

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/commands.py", line 398, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/commands.py", line 611, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/commands.py", line 1501, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/commands.py", line 1568, in _extract_package
    ret = self._run([which('npm'), 'pack', source], cwd=tempdir)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/commands.py", line 1742, in _run
    return proc.wait()

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/jupyterlab/commands.py", line 107, in wait
    out, _ = proc.communicate(timeout=.1)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/subprocess.py", line 1574, in _communicate
    self.stdout.errors)

  File "/nobackup/users/florin/anaconda3/envs/wmlce-1.6.2/lib/python3.6/subprocess.py", line 760, in _translate_newlines
    data = data.decode(encoding, errors)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 23: ordinal not in range(128)

Exiting application: jupyter
```

**Comment by jacobtomlinson** [comment]
Sorry to hear you're having trouble.

That log message seems to suggest the error is happening in `jupyterlab_tensorboard`.

Do you also have this extension installed? https://github.com/chaoleili/jupyterlab_tensorboard

**Comment by ticlazau** [comment]
Hi, no I don't have but it seems that I have the same error with that plugin when I tried to install. 
This issue is on two systems I have access based on Anaconda3 (3.6)

**Comment by jacobtomlinson** [comment]
A similar issue also seems to have been raised on the [Jupyter Forums](https://discourse.jupyter.org/t/cant-install-any-extensions-ascii-codec-cannot-decode-byte/2044).

Given that you are also having the same error with other extensions and the error is related to Jupyter Lab rather than this package I'm going to propose that you investigate whether there is something wrong with your Jupyter Lab setup.

Perhaps try installing some more extensions to see whether this issue affects them all.

**Comment by jacobtomlinson** [comment]
I'm going to close this issue for now as being unrelated to `jupyterlab-nvdashboard`. However if you do manage to narrow it down to a problem with this package I'd be happy to open it up again.
