### ISSUE TITLE
500 Error(raise NotImplementedError) when starting Jupyter lab with nvdashboard

### ISSUE THREAD

**Issue by dosp0911** [rapidsai/jupyterlab-nvdashboard#48]
Errors that I've got while running jupyter lab are as below. I think it is something to do with web connection as you see. please let me know what I should do

```
[E 19:08:53.815 LabApp] Uncaught exception GET /nvdashboard/index.json?1583921333810 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/nvdashboard/index.json?1583921333810', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\site-packages\jupyter_server_proxy\websocket.py", line 96, in get
        return await self.http_get(*args, **kwargs)
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\site-packages\jupyter_server_proxy\handlers.py", line 507, in http_get
        return await self.proxy(self.port, path)
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\site-packages\jupyter_server_proxy\handlers.py", line 501, in proxy
        await self.ensure_process()
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\site-packages\jupyter_server_proxy\handlers.py", line 478, in ensure_process
        await proc.start()
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\site-packages\simpervisor\process.py", line 91, in start
        *self._proc_args, **self._proc_kwargs
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\asyncio\subprocess.py", line 225, in create_subprocess_exec
        stderr=stderr, **kwds)
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 1211, in subprocess_exec
        bufsize, **kwargs)
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\asyncio\coroutines.py", line 212, in coro
        res = func(*args, **kw)
      File "c:\users\dskim\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 360, in _make_subprocess_transport
        raise NotImplementedError
    NotImplementedError
[E 19:08:53.867 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Authorization": "token e66646d709f1ce34a26145e0f5cf4e7faf5f170e997d94da",
      "Sec-Fetch-Dest": "empty",
      "X-Xsrftoken": "2|76605232|277c908fedab792ca40722cf47679d3e|1583914903",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8888/lab/workspaces/auto-o?clone",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh;q=0.5",
      "Cookie": "username-localhost-8889=\"2|1:0|10:1582371083|23:username-localhost-8889|44:ZmRiOWFhZGRhMDRkNGViMjg3OWRiNDZjNDA3MjhmZWU=|81cbd75c97432b07cef5ca26401ede519c0ce3e9d1959d64d9cdb77d931efb4e\"; _xsrf=2|76605232|277c908fedab792ca40722cf47679d3e|1583914903; username-localhost-8888=\"2|1:0|10:1583921333|23:username-localhost-8888|44:MzlhODQ2YTQzYTc4NDk1OGEzNzg0OWIzYjg1NDNlZTI=|5f5c08ef9e8533eab41c12cd434c829c931b708210eec58b3b03dd75105a50ec\""
    }
[E 19:08:53.871 LabApp] 500 GET /nvdashboard/index.json?1583921333810 (::1) 54.11ms referer=http://localhost:8888/lab/workspaces/auto-o?clone
[I 19:08:54.357 LabApp] Build is up to date
[I 19:09:01.227 LabApp] Kernel started: 27c5c683-1d91-4bfe-b2ce-c7d81fab859f
[I 19:09:05.252 LabApp] Kernel started: 5b0a2ac5-f655-49a8-b111-f8b95333fe69
```

**Comment by jakirkham** [comment]
Are you using JupyterLab 2? If so, that is not supported yet ( https://github.com/rapidsai/jupyterlab-nvdashboard/issues/51 ). Would downgrade to JupyterLab 1

**Comment by dosp0911** [comment]
I'm using Jupyter Lab 1.2.3. Is there something else I need to check?

**Comment by jakirkham** [comment]
Downgrade to Bokeh 1?

**Comment by cataluna84** [comment]
@dosp0911 Have you resolved it? I am facing a similar problem

**Comment by cataluna84** [comment]
Just found out, that nvdashboard does not support windows.

@here https://github.com/rapidsai/jupyterlab-nvdashboard#installation

**Comment by jacobtomlinson** [comment]
Closing as we do not currently support Windows.
